apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: turbo-user-role
  namespace: turbo
rules:
  - apiGroups: 
      - apps
    resources:
      - deployments
    resourceNames: 
      - kubeturbo
    verbs:
      - get
      - watch
      - update
      - patch
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames: 
      - pull-secret-name  # change name of pull secret here
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: turbo-user-role-binding
  namespace: turbo
subjects:
  - kind: ServiceAccount
    name: turbo-user
roleRef:
  kind: Role
  name: turbo-user-role
  apiGroup: rbac.authorization.k8s.io
