apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kubeturbo-deploy
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: kubeturbo-deploy
    name: kubeturbo-operator
  name: turbo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeturbo-deploy
    app.kubernetes.io/instance: kubeturbo-operator-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: kubeturbo-deploy
  name: kubeturbo-operator
  namespace: turbo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeturbo-operator
rules:
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - nodes
  - pods
  - configmaps
  - endpoints
  - events
  - deployments
  - persistentvolumeclaims
  - replicasets
  - replicationcontrollers
  - services
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  - apps
  - extensions
  - policy
  resources:
  - daemonsets
  - endpoints
  - limitranges
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  - poddisruptionbudget
  - resourcequotas
  - services
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/spec
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeturbo-deploy
    app.kubernetes.io/instance: kubeturbo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: kubeturbo-deploy
  name: kubeturbo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeturbo-operator
subjects:
- kind: ServiceAccount
  name: kubeturbo-operator
  namespace: turbo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kubeturbo-deploy
    app.kubernetes.io/instance: kubeturbo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: kubeturbo-deploy
    name: kubeturbo-operator
  name: kubeturbo-operator
  namespace: turbo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubeturbo-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: kubeturbo-operator
      labels:
        name: kubeturbo-operator
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: icr.io/cpopen/kubeturbo-operator:8.14.5-SNAPSHOT
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: kubeturbo-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubeturbo-operator
      terminationGracePeriodSeconds: 10
