{{- if .Values.restAPIConfig.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.restAPIConfig.turbonomicCredentialsSecretName | default "turbonomic-credentials" | quote }}
  labels:
    app.kubernetes.io/name: {{ include "kubeturbo.name" . }}
    helm.sh/chart: {{ include "kubeturbo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  clientid: {{ .Values.restAPIConfig.clientId | required "restAPIConfig.clientId is required when createSecret is true" | quote }}
  clientsecret: {{ .Values.restAPIConfig.clientSecret | required "restAPIConfig.clientSecret is required when createSecret is true" | quote }}
{{- end }}
