apiVersion: v1
kind: ConfigMap
metadata:
  name: turbodif-config-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  turbodif-config.json: |-
    {
      "communicationConfig": {
        "serverMeta": {
        {{- if .Values.serverMeta.proxy }}
          "proxy": "{{ .Values.serverMeta.proxy }}",
        {{- end }}
          "turboServer": "{{ .Values.serverMeta.turboServer }}"
        },
        "restAPIConfig": {
          "opsManagerUserName": "{{ .Values.restAPIConfig.opsManagerUserName }}",
          "opsManagerPassword": "{{ .Values.restAPIConfig.opsManagerPassword }}"
        },
        "sdkProtocolConfig": {
           "registrationTimeoutSec": {{ .Values.sdkProtocolConfig.registrationTimeoutSec }},
           "restartOnRegistrationTimeout": {{ .Values.sdkProtocolConfig.restartOnRegistrationTimeout }}
        }
      }
      {{- if .Values.targetName }}
      ,
      "targetConfig": {
        "targetName": "{{ .Values.targetName }}",
        "targetAddress": "http://127.0.0.1:8081/metrics"
      }
      {{- end }}
    }
  turbo-autoreload.config: |-
    {
      "logging": {
        "level": {{ .Values.logging.level }}
      }
    }
  turbodif-probe-config.yaml: |
    probeConf:
      probeCategory: Observability
      probeUICategory: Observability
      targetType: Prometheus
      turboLite: false
      accountDefinitions:
      - name: targetIdentifier
        displayName: Name
        description: Name for the prometurbo metric server endpoint
        verificationRegex: .*
        isRequired: true
        isSecret: false
      - name: address
        displayName: URL
        description: HTTP URL for the prometurbo metric server
        verificationRegex: .*
        isRequired: true
        isSecret: false
      - name: probeVersion
        displayName: Prometurbo Version
        description: Release Version of the Prometurbo Probe
        verificationRegex: .*
        isRequired: false
        isSecret: false
      - name: operatorVersion
        displayName: Prometurbo Operator Version
        description: Version of the Prometurbo Operator
        verificationRegex: .*
        isRequired: false
        isSecret: false
      supplyChainConfig:

