---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: 
    - ""
    - apps
  resources: 
    - pods
    - replicasets
    - secrets
  verbs: 
    - get
    - list
- apiGroups: 
    - apps
    - metrics.turbonomic.io
  resources: 
    - deployments
    - prometheusquerymappings
    - prometheusserverconfigs
  verbs: 
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
