apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
{{- if eq (include "inputClusterRoleName" .) "prometurbo" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clusterRoleName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.turbonomic.io
    resources:
      - prometheusquerymappings
      - prometheusserverconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
{{- end }}
---
kind: ClusterRoleBinding
# For OpenShift 3.4-3.7 use apiVersion: v1
# For kubernetes 1.9 use rbac.authorization.k8s.io/v1
# For kubernetes 1.8 use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "clusterRoleBindingName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
  # accepted values cluster-reader disc and monitoring.
  name: {{ include "clusterRoleName" . }}
  # For OpenShift v3.4 remove apiGroup line
  apiGroup: rbac.authorization.k8s.io

